import React, { useState, useCallback, useEffect } from 'react';
import { SearchBar } from './components/SearchBar';
import { ContentDisplay } from './components/ContentDisplay';
import { SuggestionChips } from './components/SuggestionChips';
import { SavedEntries } from './components/SavedEntries';
import { generateFullBiosphereEntry } from './services/geminiService';
import { SUGGESTION_TOPICS } from './constants';
import { SparklesIcon } from './components/icons/SparklesIcon';
import { Entry } from './types';
import { downloadTextFile } from './utils/fileUtils';

const App: React.FC = () => {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [currentEntry, setCurrentEntry] = useState<Entry | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [savedEntries, setSavedEntries] = useState<Entry[]>([]);

  useEffect(() => {
    try {
      const storedEntries = localStorage.getItem('biosphere-saved-entries');
      if (storedEntries) {
        setSavedEntries(JSON.parse(storedEntries));
      }
    } catch (e) {
      console.error("Failed to parse saved entries from localStorage", e);
      setSavedEntries([]);
    }
  }, []);

  const updateAndStoreSavedEntries = (entries: Entry[]) => {
    setSavedEntries(entries);
    localStorage.setItem('biosphere-saved-entries', JSON.stringify(entries));
  };
  
  const handleGenerate = useCallback(async (topic: string) => {
    if (!topic || isLoading) return;

    setIsLoading(true);
    setCurrentEntry(null);
    setError(null);

    try {
      const { text, imageUrl } = await generateFullBiosphereEntry(topic);
      setCurrentEntry({
        id: `${Date.now()}-${topic.replace(/\s+/g, '-')}`, // More robust ID
        topic,
        text,
        imageUrl,
      });
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : 'An unknown error occurred. Please try again.');
    } finally {
      setIsLoading(false);
    }
  }, [isLoading]);

  const handleSaveEntry = () => {
    if (currentEntry && !savedEntries.some(e => e.id === currentEntry.id)) {
      const newSavedEntries = [currentEntry, ...savedEntries];
      updateAndStoreSavedEntries(newSavedEntries);
    }
  };

  const handleDeleteEntry = (idToDelete: string) => {
    const newSavedEntries = savedEntries.filter(entry => entry.id !== idToDelete);
    updateAndStoreSavedEntries(newSavedEntries);
  };
  
  const handleSelectSavedEntry = (entry: Entry) => {
    setCurrentEntry(entry);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleDownload = () => {
    if (currentEntry) {
      downloadTextFile(currentEntry.topic, currentEntry.text);
    }
  };

  const isCurrentEntrySaved = currentEntry ? savedEntries.some(e => e.id === currentEntry.id) : false;

  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 font-sans p-4 sm:p-6 lg:p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl">
        <header className="text-center mb-8">
          <div className="flex items-center justify-center gap-3 mb-2">
            <SparklesIcon className="w-8 h-8 text-cyan-400" />
            <h1 className="text-4xl sm:text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-teal-500">
              Omniverse Biosphere
            </h1>
          </div>
          <p className="text-slate-400">Your AI guide to an infinite sanctuary of life.</p>
        </header>

        <main>
          <SearchBar onGenerate={handleGenerate} isLoading={isLoading} />
          <SuggestionChips topics={SUGGESTION_TOPICS} onSelect={handleGenerate} disabled={isLoading} />
          <ContentDisplay 
            isLoading={isLoading} 
            entry={currentEntry}
            error={error}
            onSave={handleSaveEntry}
            onDownload={handleDownload}
            isSaved={isCurrentEntrySaved}
          />
          <SavedEntries
            entries={savedEntries}
            onSelect={handleSelectSavedEntry}
            onDelete={handleDeleteEntry}
          />
        </main>
        
        <footer className="text-center mt-12 text-slate-500 text-sm">
          <p>Powered by Gemini. All content is generated by AI.</p>
          <p>&copy; {new Date().getFullYear()} Biosphere Dynamics Corp.</p>
        </footer>
      </div>
    </div>
  );
};

export default App;
